version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - $PWD:/app
      # - /app/node_modules # Exclude node_modules to avoid permission issues
    environment:
      - NODE_ENV=development
