version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            # - dist
            # - src/ # Don't rebuild for source changes
        # - action: rebuild
        #   path: package.json
        #   ignore:
        #     - node_modules/
        #     - src/ # Don't rebuild for source changes
    environment:
      NODE_ENV: development
